apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: iris-api
        image: iris-api:v1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: API_LOG_LEVEL
          value: "warn"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - iris-api
            topologyKey: kubernetes.io/hostname
