apiVersion: v1
kind: Namespace
metadata:
  name: iris-dev
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: iris-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: iris-prod
  labels:
    environment: production
